services:
  - type: web
    name: four-hands
    env: node
    plan: starter
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: HUGGINGFACE_API_KEY
        scope: build
        sync: false
      - key: PORT
        value: 3000
